ansible_user: ansible                                                 # ansible sudo user on the server
ansible_become_password: ansiblesudopassword                          # ansible sudo user sudo password (if configured)
ansible_ssh_private_key_file: /home/yourlocaluser/.ssh/id_rsa         # ssh key for on the control node for the ansible user

# software packages urls / versions
var_download_url_navidrome: https://github.com/navidrome/navidrome/releases/download/v0.52.0/navidrome_0.52.0_linux_amd64.tar.gz
var_download_url_spdl: https://github.com/spotDL/spotify-downloader/releases/download/v4.2.1/spotdl-4.2.1-linux
var_download_url_ytdlp: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
var_download_url_ytdlpweb: https://github.com/Ahimgit/yt-dlp-web/releases/download/v0.0.1/yt-dlp-web-linux-amd64.tar.gz
var_download_url_navidromealexa: https://github.com/Ahimgit/navidrome-alexa/releases/download/v0.0.3/na-linux-amd64.tar.gz

var_caddy_local_network_cidr: 192.168.1.0/24                          # cidr block for local access in caddy configs

var_navidrome_spotify_api_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           # spotify api key for navidrome
var_navidrome_spotify_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
var_navidrome_music_folder: /media/music                              # navidrome music folder
var_navidrome_data_folder: /media/navidrome                           # navidrome data folder

var_navidrome_domain_type: cloudflare.com                             # inadyn dyndns client domain type
var_navidrome_domain: navi.yourdomain.name                            # navidrome domain name
var_navidrome_domain_username: yourdomain.name                        # if using cloudflare this is your "site" name
var_navidrome_domain_password: xxxxxxxxxxxxxxxx_xxxxxxxx-xxxxxxxxx    # cloudfare api key

var_ytdl_binary: yt-dlp-web-linux-amd64                                        # binary name for systemd

var_navidromealexa_binary: na-linux-amd64                                      # binary name for systemd
var_navidromealexa_amazon_user: amazon_user@email.com                          # amazon user that owns alexa devices to use for playback
var_navidromealexa_amazon_password: xxxxxxxxxxxxxxxxx                          # amazon user password
var_navidromealexa_skill_id: amzn1.ask.skill.xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx   # alexa skill id configured for AskNavidrome skill
var_navidromealexa_api_key:  xxxxxxxxxxxxxxxxx                                 # api key for the navidrome-alexa apis
var_navidromealexa_domain_type: cloudflare.com
var_navidromealexa_domain: alexa.yourdomain.name                               # navidrome-alexa skill and api domain name
var_navidromealexa_domain_username: yourdomain.name
var_navidromealexa_domain_password: xxxxxxxxxxxxxxxx_xxxxxxxx-xxxxxxxxx