- name: Navidrome homeserver playbook
  become: yes
  hosts: all
  roles:
    - role: app_install
      tags: caddy
      vars:
        var_packages:
          - caddy
        var_upload_files_templated:
          - src: caddy.caddyfile.template
            dest: /etc/caddy/Caddyfile
            mode: "0664"
        var_systemd_service: caddy # restart existing service created by the package manager

    - role: app_install
      tags: navi
      vars:
        var_user: navidrome
        var_packages:
          - ffmpeg
        var_dirs:
          - dest: "{{ var_navidrome_music_folder }}"
          - dest: "{{ var_navidrome_data_folder }}"
        var_upload_files_templated:
          - src: navidrome.config.template
            dest: /var/lib/navidrome/navidrome.toml
            owner: "{{ var_user }}"
            group: "{{ var_user }}"
        var_download_files:
          - url: "{{ var_download_url_navidrome }}"
            dest: /opt/navidrome/navidrome.tar.gz
        var_caddy_template: navidrome.caddy.template
        var_systemd_template: navidrome.systemd.template

    - role: app_install
      tags: spdl
      vars:
        var_user: spdl
        var_packages:
          - ffmpeg
        var_dirs:
          - dest: "{{ var_navidrome_music_folder }}/downloads/spdl"
        var_download_files:
          - url: "{{ var_download_url_spdl }}"
            dest: /opt/spdl/spdl
            owner: "{{ var_user }}"
            group: "{{ var_user }}"
        var_caddy_template: spdl.caddy.template
        var_systemd_template: spdl.systemd.template

    - role: app_install
      tags: ytdl
      vars:
        var_user: ytdl
        var_packages:
          - ffmpeg
        var_dirs:
          - dest: "{{ var_navidrome_music_folder }}/downloads/ytdl"
        var_download_files:
          - url: "{{ var_download_url_ytdlp }}"
            dest: /opt/ytdl/yt-dlp
            owner: "{{ var_user }}"
            group: "{{ var_user }}"
          - url: "{{ var_download_url_ytdlpweb }}"
            dest: /opt/ytdl/
            owner: "{{ var_user }}"
            group: "{{ var_user }}"
        # var_upload_files: # a local build
        #   - src: ../../yt-dlp-web/build/yt-dlp-web
        #     dest: /opt/ytdl/yt-dlp-web-linux-amd64
        #     owner: "{{ var_user }}"
        #     group: "{{ var_user }}"
        #     mode: "0755"
        var_caddy_template: ytdl.caddy.template
        var_systemd_template: ytdl.systemd.template

    - role: app_install
      tags: asknavi
      vars:
        var_user: asknavi
        var_packages:
          - python3
          - python3-pip
        var_git_files:
          - url: "{{ var_download_url_asknavidrome }}"
            version: "{{ var_download_url_asknavidrome_ver }}"
            dest: /opt/asknavi/asknavidrome
            owner: "{{ var_user }}"
            group: "{{ var_user }}"
        var_python_venvs:
          - requirements_path: /opt/asknavi/asknavidrome/skill/requirements-full.txt
            venv_path: /opt/asknavi/venv/
            owner: "{{ var_user }}"
            group: "{{ var_user }}"
        var_caddy_template: asknavi.caddy.template
        var_systemd_template: asknavi.systemd.template

    - role: inadyn_domains
      tags: dns
      vars:
        var_dns_providers:
          - type: "{{ var_navidrome_domain_type }}"
            hostname: "{{ var_navidrome_domain }}"
            username: "{{ var_navidrome_domain_username }}"
            password: "{{ var_navidrome_domain_password }}"
          - type: "{{ var_asknavidrome_domain_type }}"
            hostname: "{{ var_asknavidrome_domain }}"
            username: "{{ var_asknavidrome_domain_username }}"
            password: "{{ var_asknavidrome_domain_password }}"
